// Copyright 2026 Merkle Works
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//


package main

import (
	"fmt"
	"os"

	ec "github.com/bsv-blockchain/go-sdk/primitives/ec"
)

func main() {
	// Don't overwrite an existing .env
	if _, err := os.Stat(".env"); err == nil {
		fmt.Println(".env already exists — not overwriting.")
		fmt.Println("Delete it first if you want a fresh key.")
		os.Exit(0)
	}

	// Generate a new BSV private key
	key, err := ec.NewPrivateKey()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating key: %s\n", err)
		os.Exit(1)
	}
	wif := key.Wif()

	// Write .env with the key and required settings
	envContent := fmt.Sprintf(`# x402 Gateway Configuration (generated by keygen)

# BSV private key (WIF format) for the delegator
BSV_PRIVATE_KEY=%s

# BSV network: "mainnet" or "testnet"
BSV_NETWORK=testnet

# Server port
PORT=8402

# Nonce pool settings
NONCE_POOL_SIZE=100

# Fee rate in sat/byte (BSV standard: 1 sat/KB = 0.001 sat/byte)
FEE_RATE=0.001

# Broadcaster: "mock" (demo/offline) or "woc" (WhatsOnChain testnet/mainnet)
BROADCASTER=mock

# Redis (set to true for production with persistent UTXO pools)
REDIS_ENABLED=false

# Template mode: Profile B (gateway pre-signs nonce input, delegator adds fee)
# Required for Developer Playground "Run Full Flow"
TEMPLATE_MODE=true
TEMPLATE_PRICE_SATS=100

# Embedded delegator (handles /delegate/x402 without a separate process)
DELEGATOR_EMBEDDED=true

# Disable treasury watcher in demo (no external API calls)
TREASURY_POLL_INTERVAL=0
`, wif)

	if err := os.WriteFile(".env", []byte(envContent), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing .env: %s\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated testnet key: %s\n", wif)
	fmt.Println("Written to .env")
}
