// Copyright 2026 Merkle Works
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//


package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	ec "github.com/bsv-blockchain/go-sdk/primitives/ec"
	"github.com/bsv-blockchain/go-sdk/script"
	"github.com/bsv-blockchain/go-sdk/transaction"
	sighash "github.com/bsv-blockchain/go-sdk/transaction/sighash"
	"github.com/bsv-blockchain/go-sdk/transaction/template/p2pkh"
	"github.com/redis/go-redis/v9"

	"github.com/merkle-works/x402-gateway/internal/challenge"
	"github.com/merkle-works/x402-gateway/internal/config"
	"github.com/merkle-works/x402-gateway/internal/delegator"
	"github.com/merkle-works/x402-gateway/internal/gatekeeper"
	"github.com/merkle-works/x402-gateway/internal/pool"
)

// x402ClientSigHash is SIGHASH_ALL | ANYONECANPAY | FORKID = 0xC1.
// Client inputs must use this flag so the delegator can append fee inputs.
var x402ClientSigHash = sighash.Flag(sighash.AllForkID | sighash.AnyOneCanPay)

// seedDemoPools populates nonce, fee, and payment pools with synthetic UTXOs so
// the full 402 → proof → 200 flow works locally without any blockchain.
// Three pools:
//   - Nonce pool: 1-sat UTXOs for replay protection
//   - Fee pool: 1-sat UTXOs for miner fees
//   - Payment pool: 100-sat UTXOs for service payments
//
// Works with both MemoryPool and RedisPool (uses Pool interface).
func seedDemoPools(noncePool, feePool, paymentPool pool.Pool, count int, feeRate float64, logger *slog.Logger) {
	// Seed nonce pool: N × 1-sat UTXOs for replay protection
	nonceScript, err := noncePool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get nonce locking script", "error", err)
		return
	}

	nonceUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		nonceUTXOs[i] = pool.UTXO{
			TxID:     syntheticTxID(i),
			Vout:     0,
			Script:   nonceScript,
			Satoshis: 1,
		}
	}
	noncePool.AddExisting(nonceUTXOs)

	// Seed fee pool: N × 1-sat UTXOs
	feeScript, err := feePool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get fee locking script", "error", err)
		return
	}

	feeUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		feeUTXOs[i] = pool.UTXO{
			TxID:     syntheticTxID(count + i), // offset to avoid txid collision
			Vout:     0,
			Script:   feeScript,
			Satoshis: 1,
		}
	}
	feePool.AddExisting(feeUTXOs)

	// Seed payment pool: N × 100-sat UTXOs for service payments
	paymentScript, err := paymentPool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get payment locking script", "error", err)
		return
	}

	paymentUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		paymentUTXOs[i] = pool.UTXO{
			TxID:     syntheticTxID(2*count + i), // offset to avoid txid collision
			Vout:     0,
			Script:   paymentScript,
			Satoshis: 100,
		}
	}
	paymentPool.AddExisting(paymentUTXOs)

	logger.Info("demo mode: pools seeded",
		"nonce_utxos", count,
		"fee_utxos", count,
		"payment_utxos", count,
		"nonce_sats", 1,
		"fee_sats", 1,
		"payment_sats", 100,
		"fee_rate", feeRate,
	)
}

// syntheticTxID generates a unique 64-char hex txid.
// First 4 bytes encode the index for debuggability; remaining 28 bytes are random.
func syntheticTxID(index int) string {
	b := make([]byte, 32)
	rand.Read(b) //nolint:errcheck // crypto/rand never fails on supported platforms
	b[0] = byte(index >> 24)
	b[1] = byte(index >> 16)
	b[2] = byte(index >> 8)
	b[3] = byte(index)
	return hex.EncodeToString(b)
}

// isSyntheticTxID returns true if the txid was generated by syntheticTxID().
// Synthetic txids encode the index in the first 4 bytes (big-endian). For
// pool sizes up to 65535, the first 2 bytes are always 0x0000, so the hex
// txid starts with "0000". Real BSV txids virtually never match this pattern
// (~1 in 65536 probability). This catches all pool offsets including payment
// pool indices (2*count + i) which can exceed 255 and set the 3rd byte > 0.
func isSyntheticTxID(txid string) bool {
	return len(txid) == 64 && strings.HasPrefix(txid, "0000")
}

// cleanDemoResiduals selectively removes synthetic (demo) UTXOs from Redis
// pools while preserving real UTXOs created by fan-out transactions.
// Called on startup in live mode to ensure only real on-chain UTXOs remain.
func cleanDemoResiduals(rdb *redis.Client, logger *slog.Logger) {
	if rdb == nil {
		return
	}

	ctx := context.Background()
	prefixes := []string{"nonce:", "fee:", "payment:"}

	for _, prefix := range prefixes {
		removed := 0
		preserved := 0

		// Scan all detail keys for this pool prefix
		pattern := prefix + "details:*"
		iter := rdb.Scan(ctx, 0, pattern, 100).Iterator()

		for iter.Next(ctx) {
			detKey := iter.Val()
			data, err := rdb.HGetAll(ctx, detKey).Result()
			if err != nil || len(data) == 0 {
				continue
			}

			txid := data["txid"]
			if isSyntheticTxID(txid) {
				// Remove synthetic UTXO from all data structures
				vout := data["vout"]
				outpoint := txid + ":" + vout
				rdb.ZRem(ctx, prefix+"available", outpoint)
				rdb.SRem(ctx, prefix+"spent", outpoint)
				rdb.Del(ctx, detKey)
				removed++
			} else {
				preserved++
			}
		}

		// Recompute stats from remaining real UTXOs
		available, _ := rdb.ZCard(ctx, prefix+"available").Result()
		spent, _ := rdb.SCard(ctx, prefix+"spent").Result()
		rdb.HSet(ctx, prefix+"stats",
			"availableUtxos", available,
			"spentUtxos", spent,
			"totalAdded", available+spent,
			"lastUpdate", fmt.Sprintf("%d", time.Now().Unix()),
		)

		logger.Info("demo residual cleanup",
			"prefix", prefix,
			"synthetic_removed", removed,
			"real_preserved", preserved,
			"available_after", available,
		)
	}
}

// ──── HTTP Handlers ────

// buildProofRequest is the JSON body for POST /demo/build-proof.
type buildProofRequest struct {
	ChallengeEncoded string `json:"challenge"` // base64url-encoded challenge from X402-Challenge
}

// buildProofResponse is the JSON response from POST /demo/build-proof.
type buildProofResponse struct {
	ProofHeader   string `json:"proof_header"`   // ready to use as X402-Proof value
	TxID          string `json:"txid"`           // for display
	ChallengeHash string `json:"challenge_hash"` // for display
}

// demoClientDeps holds the client-side keys and pools needed by the demo
// handler to construct partial transactions (acting AS the client).
type demoClientDeps struct {
	nonceKey    *ec.PrivateKey
	paymentKey  *ec.PrivateKey
	noncePool   pool.Pool
	paymentPool pool.Pool
	broadcaster transaction.Broadcaster
}

// handleBuildProof builds a complete proof server-side so the dashboard
// doesn't need BSV crypto. Per canonical spec, this endpoint:
//  1. Decodes the challenge
//  2. Constructs a partial tx (nonce input + payment input + payee output)
//  3. Signs the client inputs with 0xC1 sighash
//  4. Sends the partial tx to the delegator for fee addition
//  5. Broadcasts the completed transaction (client responsibility per spec)
//  6. Builds a spec-compliant proof with the completed transaction
func handleBuildProof(deps demoClientDeps, deleg *delegator.Delegator, payeeLockingScriptHex string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req buildProofRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{
				"error": "invalid request body: " + err.Error(),
			})
			return
		}

		// 1. Decode the challenge
		ch, err := challenge.Decode(req.ChallengeEncoded)
		if err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]any{
				"error": "decode challenge: " + err.Error(),
			})
			return
		}

		// 2. Compute challenge hash
		challengeHash, err := challenge.ComputeHash(ch)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "compute challenge hash: " + err.Error(),
			})
			return
		}

		// 3. Construct partial transaction (acting as the client)
		partialTx, nonceOutpoint, err := buildPartialTx(deps, ch, payeeLockingScriptHex)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "build partial tx: " + err.Error(),
			})
			return
		}

		// 4. Send partial tx to delegator for fee addition
		delegReq := delegator.DelegationRequest{
			PartialTxHex:                  partialTx.Hex(),
			ChallengeHash:                 challengeHash,
			ExpectedPayeeLockingScriptHex: payeeLockingScriptHex,
			ExpectedAmount:                ch.AmountSats,
			NonceOutpoint:                 nonceOutpoint,
		}

		delegResult, err := deleg.Accept(delegReq)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "delegation failed: " + err.Error(),
			})
			return
		}

		// 5. Broadcast the completed transaction (client responsibility per spec).
		//    The gatekeeper will check the mempool for this txid when the client
		//    retries with the proof — so the tx must be broadcast first.
		completedTx, err := transaction.NewTransactionFromHex(delegResult.RawTxHex)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "parse completed tx: " + err.Error(),
			})
			return
		}
		if deps.broadcaster != nil {
			_, failure := deps.broadcaster.Broadcast(completedTx)
			if failure != nil {
				slog.Warn("broadcast failed (non-fatal)", "txid", delegResult.TxID,
					"code", failure.Code, "desc", failure.Description)
			} else {
				slog.Info("client broadcast complete", "txid", delegResult.TxID)
			}
		}

		// 6. Build spec-compliant proof from the completed tx
		rawTxBytes, err := hex.DecodeString(delegResult.RawTxHex)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "decode rawtx: " + err.Error(),
			})
			return
		}
		rawTxB64 := base64.StdEncoding.EncodeToString(rawTxBytes)

		// Compute body and headers hash (empty for GET from dashboard)
		bodyHash := challenge.HashBody(nil)
		emptyHeaders := make(http.Header)
		headersHash := challenge.HashHeaders(emptyHeaders, gatekeeper.HeaderAllowlist)

		proof := &gatekeeper.Proof{
			V:               challenge.Version,
			Scheme:          challenge.Scheme,
			TxID:            delegResult.TxID,
			RawTxB64:        rawTxB64,
			ChallengeSHA256: challengeHash,
			Request: gatekeeper.RequestBinding{
				Domain:           ch.Domain,
				Method:           ch.Method,
				Path:             ch.Path,
				Query:            ch.Query,
				ReqHeadersSHA256: headersHash,
				ReqBodySHA256:    bodyHash,
			},
		}
		proofEncoded, err := gatekeeper.EncodeProof(proof)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError, map[string]any{
				"error": "encode proof: " + err.Error(),
			})
			return
		}

		writeJSON(w, http.StatusOK, buildProofResponse{
			ProofHeader:   proofEncoded,
			TxID:          delegResult.TxID,
			ChallengeHash: challengeHash,
		})
	}
}

// buildPartialTx constructs a partial transaction with client inputs signed
// using SIGHASH_ALL|ANYONECANPAY|FORKID (0xC1). This is the canonical client
// behaviour per spec: the client provides inputs and signs them so that the
// delegator can append fee inputs without invalidating client signatures.
func buildPartialTx(deps demoClientDeps, ch *challenge.Challenge, payeeLockingScriptHex string) (*transaction.Transaction, *delegator.NonceOutpointRef, error) {
	if ch.NonceUTXO == nil {
		return nil, nil, fmt.Errorf("challenge has no nonce_utxo")
	}

	tx := transaction.NewTransaction()

	// Input 0: nonce UTXO (signed with nonceKey, 0xC1)
	nonceUnlocker, err := p2pkh.Unlock(deps.nonceKey, &x402ClientSigHash)
	if err != nil {
		return nil, nil, fmt.Errorf("create nonce unlocker: %w", err)
	}

	err = tx.AddInputFrom(
		ch.NonceUTXO.TxID,
		ch.NonceUTXO.Vout,
		ch.NonceUTXO.LockingScriptHex,
		ch.NonceUTXO.Satoshis,
		nonceUnlocker,
	)
	if err != nil {
		return nil, nil, fmt.Errorf("add nonce input: %w", err)
	}

	// Input 1: payment UTXO (signed with paymentKey, 0xC1)
	paymentUTXO, err := deps.paymentPool.Lease()
	if err != nil {
		return nil, nil, fmt.Errorf("lease payment UTXO: %w", err)
	}

	paymentUnlocker, err := p2pkh.Unlock(deps.paymentKey, &x402ClientSigHash)
	if err != nil {
		return nil, nil, fmt.Errorf("create payment unlocker: %w", err)
	}

	err = tx.AddInputFrom(paymentUTXO.TxID, paymentUTXO.Vout, paymentUTXO.Script, paymentUTXO.Satoshis, paymentUnlocker)
	if err != nil {
		return nil, nil, fmt.Errorf("add payment input: %w", err)
	}

	// Output 0: payee (amount from challenge)
	payeeScriptBytes, err := hex.DecodeString(payeeLockingScriptHex)
	if err != nil {
		return nil, nil, fmt.Errorf("invalid payee script hex: %w", err)
	}
	payeeScript := script.Script(payeeScriptBytes)
	tx.AddOutput(&transaction.TransactionOutput{
		Satoshis:      uint64(ch.AmountSats),
		LockingScript: &payeeScript,
	})

	// Sign all client inputs (nonce + payment) with 0xC1 sighash
	if err := tx.Sign(); err != nil {
		return nil, nil, fmt.Errorf("sign partial tx: %w", err)
	}

	// Mark payment UTXO spent (nonce is managed by the nonce pool via challenge)
	deps.paymentPool.MarkSpent(paymentUTXO.TxID, paymentUTXO.Vout)

	nonceOutpoint := &delegator.NonceOutpointRef{
		TxID: ch.NonceUTXO.TxID,
		Vout: ch.NonceUTXO.Vout,
	}

	return tx, nonceOutpoint, nil
}

// handleDemoInfo returns server state for the dashboard.
func handleDemoInfo(cfg *config.Config, noncePool, feePool, paymentPool pool.Pool, payeeAddr string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, map[string]any{
			"version":      "1.0.0",
			"mode":         "demo",
			"network":      cfg.BSVNetwork,
			"payee":        payeeAddr,
			"port":         cfg.Port,
			"nonce_pool":   noncePool.Stats(),
			"fee_pool":     feePool.Stats(),
			"payment_pool": paymentPool.Stats(),
			"price_sats":   100,
		})
	}
}

// writeJSON encodes a value as JSON and writes it to the response.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v)
}
