// Copyright 2026 Merkle Works
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0


package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"log/slog"
	"strings"

	ec "github.com/bsv-blockchain/go-sdk/primitives/ec"
	"github.com/redis/go-redis/v9"

	"github.com/merkleworks/x402-bsv/internal/pool"
	"github.com/merkleworks/x402-bsv/internal/treasury"
)

// templateOpts holds optional Profile B template generation parameters.
type templateOpts struct {
	enabled               bool
	nonceKey              *ec.PrivateKey
	payeeLockingScriptHex string
	priceSats             uint64
}

// seedDemoPools populates nonce, fee, and payment pools with synthetic UTXOs so
// the full 402 → proof → 200 flow works locally without any blockchain.
// Three pools:
//   - Nonce pool: 1-sat UTXOs for replay protection
//   - Fee pool: feeUTXOSats-sat UTXOs for delegator funding (payment + miner fees)
//   - Payment pool: 100-sat UTXOs for service payments
//
// feeUTXOSats is the denomination per fee UTXO (from FEE_UTXO_SATS env var, 1–1000).
//
// When tmpl.enabled is true (Profile B), pre-signed templates are generated
// for each nonce UTXO before adding them to the pool.
//
// Works with both MemoryPool and RedisPool (uses Pool interface).
func seedDemoPools(noncePool, feePool, paymentPool pool.Pool, count int, feeRate float64, feeUTXOSats uint64, tmpl templateOpts, logger *slog.Logger) {
	// Seed nonce pool: N × 1-sat UTXOs for replay protection
	nonceScript, err := noncePool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get nonce locking script", "error", err)
		return
	}

	nonceUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		nonceUTXOs[i] = pool.UTXO{
			TxID:       syntheticTxID(i),
			Vout:       0,
			Script:     nonceScript,
			Satoshis:   1,
			Synthetic:  true,
			OriginMode: "mock",
		}
	}

	// Profile B: generate pre-signed templates for nonce UTXOs
	if tmpl.enabled && tmpl.nonceKey != nil {
		if err := treasury.GenerateTemplates(tmpl.nonceKey, nonceUTXOs, tmpl.payeeLockingScriptHex, tmpl.priceSats); err != nil {
			logger.Error("demo seed: failed to generate templates", "error", err)
			return
		}
		logger.Info("demo seed: generated templates for nonce UTXOs",
			"count", count,
			"price_sats", tmpl.priceSats,
			"sighash", "0xC3 (SIGHASH_SINGLE|ANYONECANPAY|FORKID)",
		)
	}

	noncePool.AddExisting(nonceUTXOs)

	// Seed fee pool: N × feeUTXOSats UTXOs for delegator funding
	feeScript, err := feePool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get fee locking script", "error", err)
		return
	}

	feeUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		feeUTXOs[i] = pool.UTXO{
			TxID:       syntheticTxID(count + i), // offset to avoid txid collision
			Vout:       0,
			Script:     feeScript,
			Satoshis:   feeUTXOSats,
			Synthetic:  true,
			OriginMode: "mock",
		}
	}
	feePool.AddExisting(feeUTXOs)

	// Seed payment pool: N × 100-sat UTXOs for service payments
	paymentScript, err := paymentPool.LockingScriptHex()
	if err != nil {
		logger.Error("demo seed: failed to get payment locking script", "error", err)
		return
	}

	paymentUTXOs := make([]pool.UTXO, count)
	for i := 0; i < count; i++ {
		paymentUTXOs[i] = pool.UTXO{
			TxID:       syntheticTxID(2*count + i), // offset to avoid txid collision
			Vout:       0,
			Script:     paymentScript,
			Satoshis:   100,
			Synthetic:  true,
			OriginMode: "mock",
		}
	}
	paymentPool.AddExisting(paymentUTXOs)

	logger.Info("demo mode: pools seeded",
		"nonce_utxos", count,
		"fee_utxos", count,
		"payment_utxos", count,
		"nonce_sats", 1,
		"fee_sats", feeUTXOSats,
		"payment_sats", 100,
		"fee_rate", feeRate,
	)
}

// syntheticTxID generates a unique 64-char hex txid.
// First 4 bytes encode the index for debuggability; remaining 28 bytes are random.
func syntheticTxID(index int) string {
	b := make([]byte, 32)
	rand.Read(b) //nolint:errcheck // crypto/rand never fails on supported platforms
	b[0] = byte(index >> 24)
	b[1] = byte(index >> 16)
	b[2] = byte(index >> 8)
	b[3] = byte(index)
	return hex.EncodeToString(b)
}

// isSyntheticTxID returns true if the txid was generated by syntheticTxID().
// Synthetic txids encode the index in the first 4 bytes (big-endian). For
// pool sizes up to 65535, the first 2 bytes are always 0x0000, so the hex
// txid starts with "0000". Real BSV txids virtually never match this pattern
// (~1 in 65536 probability). This catches all pool offsets including payment
// pool indices (2*count + i) which can exceed 255 and set the 3rd byte > 0.
func isSyntheticTxID(txid string) bool {
	return len(txid) == 64 && strings.HasPrefix(txid, "0000")
}

// detectLegacyKeys checks for un-namespaced Redis keys from before
// mode-segregated namespaces were introduced. These keys are ignored —
// data now lives under <mode>:<pool>: namespace (e.g. "live:nonce:").
// Logs a warning if legacy keys are found so operators know to clean up.
func detectLegacyKeys(rdb *redis.Client, logger *slog.Logger) {
	if rdb == nil {
		return
	}

	ctx := context.Background()
	legacyPrefixes := []string{"nonce:", "fee:", "payment:"}

	for _, prefix := range legacyPrefixes {
		count, _ := rdb.ZCard(ctx, prefix+"available").Result()
		spent, _ := rdb.SCard(ctx, prefix+"spent").Result()
		if count > 0 || spent > 0 {
			logger.Warn("legacy un-namespaced Redis keys detected",
				"prefix", prefix,
				"available", count,
				"spent", spent,
				"action", "these keys are ignored — data now lives under <mode>:<pool>: namespace",
			)
		}
	}
}
